services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=wherewasi_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=dev_password'
      - 'MONGO_INITDB_ROOT_USERNAME=dev_user'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/data/db'
  redis:
    image: 'redis:8-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
  mongo-express:
    image: 'mongo-express'
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev_password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb

volumes:
  mongodb_data:
  redis_data:
