name: CI Build

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Run Unit Tests
        run: mvn clean test

      - name: Run Integration Tests
        run: mvn verify
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Publish Test Reports
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Maven Test Results
          path: '**/surefire-reports/*.xml'
          reporter: 'java-junit'



